# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='pytesser'),
        ),
    ]
