# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170512_0820'),
    ]

    operations = [
    ]
